# Generated by Django 5.2.6 on 2026-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_degree_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fit_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fit_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_resume',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ranking_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='search_document',
            field=models.TextField(blank=True, default=''),
        ),
    ]
